name: Run CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev

      - name: Black
        run: python -m black --check src/

      - name: Pylint
        run: python -m pylint **/*.py

      - name: Set Stage for Unit Tests
        run: |
          cp config.ini.example config.ini
          cp logging_config.ini.example logging_config.ini
          mkdir logs && touch logs/gunicorn.error.log

      - name: Unit Tests
        run: python test.py
